# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartElement_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_slug', models.SlugField(max_length=255)),
                ('item_description', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('item_price', models.FloatField()),
                ('item_weight', models.FloatField()),
                ('item_height', models.FloatField()),
                ('item_width', models.FloatField()),
                ('item_deep', models.FloatField()),
                ('item_brand', models.CharField(max_length=255)),
                ('item_article', models.CharField(max_length=255)),
                ('item_picture', models.ImageField(upload_to='')),
                ('item_cartElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.CartElement')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('NOP', 'No payment'), ('SUP', 'Success payment'), ('RTS', 'Ready to ship'), ('ONT', 'In delivering'), ('ACH', 'Achieved'), ('EIP', 'Error in process')], default='NOP', max_length=3)),
                ('order_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.CartElement')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userprofile_address', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.UserProfile'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.Tag'),
        ),
        migrations.AddField(
            model_name='cartelement',
            name='cartElement_userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.UserProfile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_cartElement',
            field=models.ManyToManyField(to='outlet.CartElement'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.UserProfile'),
        ),
    ]
