# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_cartElement',
        ),
        migrations.AddField(
            model_name='item',
            name='item_cartElement',
            field=models.ManyToManyField(to='outlet.CartElement'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_liked',
        ),
        migrations.AddField(
            model_name='item',
            name='item_liked',
            field=models.ManyToManyField(to='outlet.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_tags',
        ),
        migrations.AddField(
            model_name='item',
            name='item_tags',
            field=models.ManyToManyField(to='outlet.Tag'),
        ),
    ]
